title: 'Loch Moore Farms'
author: 'niden.net'
description: 'Loch Moore Farms is a farm near Petersburg, WV.'
keywords: 'loch moore farms, kattle, sheep, petersburg, wv'
email: 'lochmoorefarms@gmail.com'
