title: 'Loch Moose Farms'
author: 'niden.net'
description: 'Loch Moose Farms is a farm near Petersburg, WV.'
keywords: 'loch moose farms, kattle, sheep, petersburg, wv'
email: 'lochmoosefarms@gmail.com'
